// src/layouts/layout.tsx
import "../app/globals.css";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import { Metadata } from "next";
import React, { createContext, useState, ReactNode } from "react";
import "../i18n";

interface MyContextProps {
  message: string;
  setMessage: (msg: string) => void;
}

export const MyContext = createContext<MyContextProps>({
  message: "",
  setMessage: () => {},
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  const [message, setMessage] = useState("Olá do contexto!");

  return (
    <MyContext.Provider value={{ message, setMessage }}>
      <html lang="pt">
        <body className="flex-col justify-center">
          <Header />
          <Hero />
          <Footer />
          <main>{children}</main>
        </body>
      </html>
    </MyContext.Provider>
  );
}
